"use client";

import { History, Lightbulb, RefreshCw, Trophy } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CampaignPostRankings } from "@/components/campaigns/campaign-post-rankings";
import type { CampaignIntelligencePost, CampaignIntelligenceReport } from "@/lib/domain/campaign-intelligence";
import type { CampaignIntelligenceHistory } from "@/lib/domain/campaign-intelligence-history";

function number(value: number | null): string { return value === null ? "—" : new Intl.NumberFormat().format(value); }
function percent(value: number | null): string { return value === null ? "—" : `${Math.round(value * 100) / 100}%`; }
function confidenceVariant(value: CampaignIntelligenceReport["dataQuality"]["confidence"]): "success" | "warning" | "danger" | "neutral" { return value === "high" ? "success" : value === "medium" ? "warning" : value === "low" ? "danger" : "neutral"; }
function postLabel(post: CampaignIntelligencePost): string { return `Post ${post.postId.slice(0, 8)}`; }
function displayClassification(value: CampaignIntelligencePost["classification"]): string { return value === "insufficient_data" ? "Insufficient data" : value.replaceAll("_", " "); }

async function errorMessage(response: Response): Promise<string> {
  const body = await response.json().catch(() => null) as { error?: { message?: string } } | null;
  return body?.error?.message ?? "Couldn't load campaign intelligence.";
}

export function CampaignIntelligencePanel({ campaignId, initialReport, initialHistory }: { campaignId: string; initialReport: CampaignIntelligenceReport; initialHistory: CampaignIntelligenceHistory }) {
  const [report, setReport] = useState(initialReport);
  const [history, setHistory] = useState(initialHistory);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);

  async function load(path = `/api/campaigns/${campaignId}/intelligence?pageSize=50`) {
    setBusy(true); setMessage(null);
    try {
      const response = await fetch(path, { cache: "no-store" });
      if (!response.ok) throw new Error(await errorMessage(response));
      const data = await response.json() as { intelligence: CampaignIntelligenceReport };
      setReport(data.intelligence);
      const historyResponse = await fetch(`/api/campaigns/${campaignId}/intelligence/history?limit=10`, { cache: "no-store" });
      if (historyResponse.ok) setHistory((await historyResponse.json() as { history: CampaignIntelligenceHistory }).history);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Couldn't load campaign intelligence.");
    } finally { setBusy(false); }
  }

  async function loadMoreHistory() {
    if (!history.nextCursor) return;
    setBusy(true); setMessage(null);
    try {
      const response = await fetch(`/api/campaigns/${campaignId}/intelligence/history?limit=10&cursor=${encodeURIComponent(history.nextCursor)}`, { cache: "no-store" });
      if (!response.ok) throw new Error(await errorMessage(response));
      const next = (await response.json() as { history: CampaignIntelligenceHistory }).history;
      setHistory((current) => ({ ...current, items: [...current.items, ...next.items], nextCursor: next.nextCursor }));
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Couldn't load more intelligence history.");
    } finally { setBusy(false); }
  }

  function togglePost(postId: string) {
    setSelectedIds((current) => current.includes(postId) ? current.filter((id) => id !== postId) : current.length >= 3 ? current : [...current, postId]);
  }

  const top = report.rankings.topPerformers;
  const underperformers = report.rankings.underperformers;
  return (
    <section aria-labelledby="campaign-intelligence-title" className="flex flex-col gap-4">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div><h2 id="campaign-intelligence-title" className="text-lg font-semibold">Content intelligence</h2><p className="text-sm text-muted-foreground">Explainable campaign signals from internal analytics snapshots.</p></div>
        <Button variant="outline" size="sm" onClick={() => void load()} disabled={busy}><RefreshCw data-icon="inline-start" className={busy ? "animate-spin" : undefined} />Refresh intelligence</Button>
      </div>
      {message ? <p role="alert" className="rounded-md border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{message}</p> : null}
      <Card className="border-primary/30 bg-primary/5"><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium">Data quality</p><p className="text-sm text-muted-foreground">{report.dataQuality.message}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant={confidenceVariant(report.dataQuality.confidence)}>{report.dataQuality.confidence} confidence</Badge><Badge variant="neutral">{percent(report.dataQuality.analyticsCoverage)} coverage</Badge><Badge variant="neutral">{report.dataQuality.freshness}</Badge></div></CardContent></Card>
      <CampaignPostRankings campaignId={campaignId} />
      <div className="grid gap-3 sm:grid-cols-4"><Card><CardContent className="p-4"><p className="text-2xl font-semibold tabular-nums">{report.overview.totalPosts}</p><p className="text-xs text-muted-foreground">Campaign posts</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-2xl font-semibold tabular-nums">{report.overview.comparablePosts}</p><p className="text-xs text-muted-foreground">Comparable posts</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-2xl font-semibold tabular-nums">{report.overview.averageScore ?? "—"}</p><p className="text-xs text-muted-foreground">Average score</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-2xl font-semibold tabular-nums">{report.overview.underperformerCount}</p><p className="text-xs text-muted-foreground">Underperformers</p></CardContent></Card></div>
      <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Trophy className="size-4 text-primary" />Top performers</CardTitle><CardDescription>Only shown when at least three posts have comparable data.</CardDescription></CardHeader><CardContent>{top.length === 0 ? <p className="text-sm text-muted-foreground">Not enough comparable data yet.</p> : <ol className="space-y-3">{top.map((post) => <li key={post.postId} className="flex items-center justify-between gap-3"><div><Link href={`/history?post=${post.postId}`} className="font-medium hover:text-primary">{postLabel(post)}</Link><p className="text-xs capitalize text-muted-foreground">{post.format} · {post.trend} · {post.confidence} confidence</p></div><span className="font-semibold tabular-nums">{post.score ?? "—"}</span></li>)}</ol>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Underperforming content</CardTitle><CardDescription>Comparative signal after the minimum observation window.</CardDescription></CardHeader><CardContent>{underperformers.length === 0 ? <p className="text-sm text-muted-foreground">No meaningful underperformance signal.</p> : <ul className="space-y-3">{underperformers.map((post) => <li key={post.postId} className="flex items-center justify-between gap-3"><Link href={`/history?post=${post.postId}`} className="font-medium hover:text-primary">{postLabel(post)}</Link><Badge variant="danger">{displayClassification(post.classification)}</Badge></li>)}</ul>}</CardContent></Card></div>
      <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Platform intelligence</CardTitle><CardDescription>Unavailable metrics remain unavailable; they are never converted to zero.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="pb-2">Platform</th><th className="pb-2">Posts</th><th className="pb-2">Coverage</th><th className="pb-2">Avg score</th><th className="pb-2">Trend</th></tr></thead><tbody>{report.platformPerformance.map((group) => <tr key={group.name} className="border-t border-border/60"><td className="py-2">{group.name}</td><td className="py-2 tabular-nums">{group.posts}</td><td className="py-2 tabular-nums">{percent(group.metricCoverage)}</td><td className="py-2 tabular-nums">{group.averageScore ?? "—"}</td><td className="py-2 capitalize">{group.trend}</td></tr>)}</tbody></table></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Format & timing</CardTitle><CardDescription>Signals are suppressed when the sample is too small.</CardDescription></CardHeader><CardContent className="space-y-3">{report.formatPerformance.length === 0 ? <p className="text-sm text-muted-foreground">No format data yet.</p> : <div className="space-y-2">{report.formatPerformance.map((group) => <div key={group.name} className="flex items-center justify-between text-sm"><span className="capitalize">{group.name}</span><span className="text-muted-foreground">{group.analyticsPosts} tracked · {group.averageScore ?? "—"} score</span></div>)}</div>}<div className="rounded-md border border-dashed border-border p-3 text-sm">{report.postingTime.status === "ready" ? <><p className="font-medium">Best test window: {report.postingTime.bestDay}, {report.postingTime.bestWindow}</p><p className="text-xs text-muted-foreground">Based on {report.postingTime.metricBasis} across {report.postingTime.sampleSize} posts.</p></> : <p className="text-muted-foreground">Not enough posting-time data yet.</p>}</div></CardContent></Card></div>
      <div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Lightbulb className="size-4 text-primary" />Insights & recommendations</CardTitle><CardDescription>Suggestions are data-backed and never mutate content automatically.</CardDescription></CardHeader><CardContent className="space-y-4">{report.insights.length === 0 && report.recommendations.length === 0 ? <p className="text-sm text-muted-foreground">No recommendations yet.</p> : <>{report.insights.map((insight) => <div key={`${insight.kind}-${insight.title}`} className="border-b border-border/60 pb-3 last:border-0"><p className="text-sm font-medium">{insight.title}</p><p className="text-sm text-muted-foreground">{insight.message}</p></div>)}{report.recommendations.map((recommendation) => <div key={recommendation.fingerprint} className="rounded-md border border-primary/20 bg-primary/5 p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">{recommendation.title}</p><Badge variant={recommendation.priority === "high" ? "danger" : recommendation.priority === "medium" ? "warning" : "neutral"}>{recommendation.priority}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{recommendation.reason}</p>{recommendation.action ? <p className="mt-2 text-xs font-medium text-primary">Suggested action: {recommendation.action}</p> : null}</div>)}</>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Goal contribution</CardTitle><CardDescription>{report.goal.metric ? `Top contributors to ${report.goal.metric}.` : "Set a campaign target to see contribution."}</CardDescription></CardHeader><CardContent>{report.goal.topContributors.length === 0 ? <p className="text-sm text-muted-foreground">No comparable goal contribution yet.</p> : <ol className="space-y-2">{report.goal.topContributors.map((post) => <li key={post.postId} className="flex items-center justify-between text-sm"><Link href={`/history?post=${post.postId}`} className="hover:text-primary">{postLabel(post)}</Link><span className="tabular-nums">{percent(post.goalContribution)}</span></li>)}</ol>}</CardContent></Card></div>
      <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Lightbulb className="size-4 text-primary" />Optimization opportunities</CardTitle><CardDescription>Prioritized signals with evidence. Nothing changes automatically.</CardDescription></CardHeader><CardContent>{report.opportunities.length === 0 ? <p className="text-sm text-muted-foreground">No active opportunity yet.</p> : <div className="space-y-3">{report.opportunities.map((opportunity) => <div key={opportunity.fingerprint} className="rounded-md border border-border/70 p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">{opportunity.title}</p><Badge variant={opportunity.priority === "high" ? "danger" : opportunity.priority === "medium" ? "warning" : "neutral"}>{opportunity.priority}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{opportunity.reason}</p><p className="mt-2 text-xs text-muted-foreground">{opportunity.confidence} confidence · {opportunity.type.replaceAll("_", " ")}</p></div>)}</div>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><History className="size-4 text-primary" />Snapshot history</CardTitle><CardDescription>Historical score and direction, newest first.</CardDescription></CardHeader><CardContent>{history.items.length === 0 ? <p className="text-sm text-muted-foreground">Run an evaluation to create the first snapshot.</p> : <div className="space-y-3">{history.items.map((snapshot) => <div key={snapshot.id} className="flex items-center justify-between gap-3 border-b border-border/60 pb-3 last:border-0 last:pb-0"><div><p className="text-sm font-medium">{snapshot.performanceScore ?? "—"} score · {snapshot.momentum} momentum</p><p className="text-xs text-muted-foreground">{snapshot.snapshotReason.replaceAll("_", " ")} · {snapshot.confidence} confidence</p></div><time className="shrink-0 text-xs text-muted-foreground" dateTime={snapshot.createdAt.toISOString()}>{new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(snapshot.createdAt))}</time></div>)}{history.nextCursor ? <Button variant="outline" size="sm" onClick={() => void loadMoreHistory()} disabled={busy}>Load more history</Button> : null}</div>}</CardContent></Card></div>
      <Card><CardHeader><CardTitle className="text-base">Compare campaign posts</CardTitle><CardDescription>Select two or three posts. Comparison is campaign-scoped and uses safe identifiers only.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{report.posts.items.map((post) => <label key={post.postId} className="flex items-center gap-2 rounded-md border border-border p-3 text-sm"><input type="checkbox" checked={selectedIds.includes(post.postId)} onChange={() => togglePost(post.postId)} /><span className="min-w-0 flex-1"><span className="block font-medium">{postLabel(post)}</span><span className="block text-xs capitalize text-muted-foreground">{post.format} · score {post.score ?? "—"}</span></span></label>)}</div><Button variant="outline" size="sm" disabled={busy || selectedIds.length < 2} onClick={() => void load(`/api/campaigns/${campaignId}/intelligence?${selectedIds.map((id) => `postId=${encodeURIComponent(id)}`).join("&")}`)}>Compare selected</Button>{report.comparison ? <div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead><tr className="text-xs text-muted-foreground"><th className="pb-2">Metric</th>{report.comparison.posts.map((post) => <th key={post.postId} className="pb-2">{postLabel(post)}</th>)}</tr></thead><tbody>{(["score", "views", "reach", "engagement", "engagementRate", "goalContribution"] as const).map((metric) => <tr key={metric} className="border-t border-border/60"><td className="py-2 capitalize">{metric.replace("engagementRate", "engagement rate")}</td>{report.comparison!.posts.map((post) => { const value = metric === "score" ? post.score : metric === "engagementRate" ? post.engagementRate.value : metric === "engagement" ? post.metrics.engagement : metric === "goalContribution" ? post.goalContribution : post.metrics[metric]; return <td key={post.postId} className={`py-2 tabular-nums ${report.comparison?.winners[metric] === post.postId ? "font-semibold text-primary" : ""}`}>{value === null ? "—" : metric === "engagementRate" ? percent(value) : number(value)}</td>; })}</tr>)}</tbody></table></div> : null}</CardContent></Card>
    </section>
  );
}
